ci: add missing properties required by nexus-staging plugin
Error: [ERROR] Rule failure while trying to close staging repository with ID "orgtestng-1085".
Error: [ERROR]
Error: [ERROR] Nexus Staging Rules Failure Report
Error: [ERROR] ==================================
Error: [ERROR]
Error: [ERROR] Repository "orgtestng-1085" failures
Error: [ERROR]   Rule "pom-staging" failures
Error: [ERROR]     * Invalid POM: /org/testng/testng-remote/testng-remote-parent/1.5.0/testng-remote-parent-1.5.0.pom: Project description missing, Project URL missing, License information missing, Developer information missing